trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - '**/*.md'

pool:
  vmImage: windows-latest

parameters:
- name: buildConfiguration
  type: string
  default: 'Release'
- name: buildPlatform
  type: string
  default: 'Any CPU'
- name: targetFrameworks
  type: object
  default:
  - '3.1.x'
  - '6.x'
  - '7.x'

variables:
  solution: 'JWT.sln'
 

steps:

- ${{ each targetFramework in parameters.targetFrameworks }}:
  - task: UseDotNet@2
    displayName: ${{ format(''Install .NET {0}', targetFramework) }}
    inputs:
      packageType: sdk
      version: ${{ targetFramework }}
      installationPath: '$(Agent.ToolsDirectory)/dotnet'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages for .NET Core'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages for .NET Framework'
  inputs:
    command: 'restore'
    restoreSolution: $(solution)

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c ${{ parameters.buildConfiguration }} --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    arguments: ' -c ${{ parameters.buildConfiguration }} --no-build --no-restore'
    testRunner: 'VSTest'
    testResultsFiles: '**/*.trx'
    testResultsFormat: 'VSTest'
    failTaskOnFailedTests: true

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet packages'
  inputs:
    command: pack
    packagesToPack: 'src/**/*.csproj'
    configuration: ${{ parameters.buildConfiguration }}
    nobuild: true

- task: CopyFiles@2
  displayName: 'Copy changelog'
  inputs:
    sourceFolder: $(Build.SourcesDirectory)
    targetFolder: $(Build.ArtifactStagingDirectory)
    contents: |
      CHANGELOG.md

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
