trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - '**/*.md'

pool:
  vmImage: windows-latest

variables:
  solution: 'JWT.sln'
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

steps:
- task: UseDotNet@2
  displayName: 'Install .NET Core 3.1.x'
  inputs:
    packageType: sdk
    version: '3.1.x'
    installationPath: '$(Agent.ToolsDirectory)/dotnet'

- task: UseDotNet@2
  displayName: 'Install .NET 6.0.x'
  inputs:
    packageType: sdk
    version: '6.0.x'
    installationPath: '$(Agent.ToolsDirectory)/dotnet'

- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages for .NET Core'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: NuGetCommand@2
  displayName: 'Restore NuGet packages for .NET Framework'
  inputs:
    command: 'restore'
    restoreSolution: $(solution)

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '-c $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: 'tests/**/*.csproj'
    arguments: ' -c $(buildConfiguration) --no-build --no-restore'
    testRunner: 'VSTest'
    testResultsFiles: '**/*.trx'
    testResultsFormat: 'VSTest'
    failTaskOnFailedTests: true

- task: DotNetCoreCLI@2
  displayName: 'Create NuGet packages'
  inputs:
    command: pack
    packagesToPack: 'src/**/*.csproj'
    configuration: $(BuildConfiguration)
    nobuild: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
